#!/usr/bin/env python
# warmup should be added into everyone's root level repository. warmup will:
# * download and set up a virtualenv
# * install uranium
# * run uranium
import sys
import os

URANIUM_PATH = os.getenv('URANIUM_PATH', None)
URANIUM_REPO = os.getenv('URANIUM_REPO', 'toumorokoshi')
URANIUM_BRANCH = os.getenv('URANIUM_BRANCH', 'master')
URANIUM_STANDALONE_URL = "https://raw.githubusercontent.com/{repo}/uranium/{branch}/uranium/scripts/uranium_standalone".format(repo=URANIUM_REPO, branch=URANIUM_BRANCH)

if URANIUM_PATH is not None:
    execfile(os.path.realpath(URANIUM_PATH))
else:
    print("Downloading uranium from " + URANIUM_STANDALONE_URL)
    try:
        from urllib2 import urlopen as urlopen
    except:
        from urllib.request import urlopen as urlopen

    print("loading uranium bootstrapper...")
    body = urlopen(URANIUM_STANDALONE_URL).read()
    exec(body)
